language: android
jdk: oraclejdk8
sudo: false

android:
  components:

    - tools
    - build-tools-19.0.1
    - android-19

    # Support library
    - extra-android-support
    - extra-android-m2repository
before_script: 
  - cd CyFile-Android
  - chmod +x gradlew

script:
  - echo "Travis branch is $TRAVIS_BRANCH"
  - echo "Travis branch is in pull request $TRAVIS_PULL+REQUEST"
  - ./gradlew
# before_cache:
#   - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
#   - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
# cache:
#   directories:
#     - $HOME/.gradle/caches/
#     - $HOME/.gradle/wrapper/
#     - $HOME/.android/build-cache  